# Default values for dummy-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: phan2410/dummy-service
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: ""

debug: true
appid: ""
port: &port 8081
entrypoint: {}
#  command: []
#  args: []
#  workingDir: ""

envVars:
  - name: DEBUG
    value: "{{ .Values.debug }}"
  - name: PORT
    value: "{{ .Values.port }}"
  - name: APPID
    value: "{{ .Values.appid | default (randAlphaNum 8) }}"

httpGetHealth: &httpGetHealth
  port: *port
  path: /internal/health

livenessProbe:
  httpGet: *httpGetHealth
  initialDelaySeconds: 5
  periodSeconds: 10
readinessProbe:
  httpGet: *httpGetHealth
  initialDelaySeconds: 5
  periodSeconds: 5
startupProbe:
  httpGet: *httpGetHealth
  initialDelaySeconds: 5
  periodSeconds: 5
  failureThreshold: 30

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""

podAnnotations:
  sidecar.istio.io/inject: "true"
  traffic.sidecar.istio.io/excludeOutboundPorts: "5432,6379"

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: *port

istio_gateway:
  enabled: false
  # The selector matches the ingress pod labels.
  # If you installed Istio using Helm following the standard documentation, this would be "istio=ingress"
  selector:
    istio: ingress
  name: ""

istio_vs:
  enabled: false
  name: ""
  gateway: ""
  http:
  - match:
    - uri:
        prefix: "/"

ingress:
  enabled: false
  name: ""
  className: "nginx"
  annotations: {}
  hosts:
    - host: "*"
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  targetMemoryUtilizationPercentage: 80

# Additional volumes on the output Deployment definition.
volumes: []
# - name: foo
#   secret:
#     secretName: mysecret
#     optional: false

# Additional volumeMounts on the output Deployment definition.
volumeMounts: []
# - name: foo
#   mountPath: "/etc/foo"
#   readOnly: true

nodeSelector: {}

tolerations: []

affinity: {}
