{{- if and .Values.istio_gateway.enabled .Values.istio_gateway.selector }}
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: {{ include "dummy-service.istioGatewayName" . }}
  labels:
      {{- include "dummy-service.labels" . | nindent 4 }}
spec:
  selector:
    {{- tpl (toYaml .Values.istio_gateway.selector) . | nindent 4 }}
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
{{- end }}