{{- if and .Values.istio_vs.enabled .Values.istio_vs.http }}
{{- $fullName := include "dummy-service.fullname" . -}}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.istio_vs.name | default $fullName }}
  labels:
      {{- include "dummy-service.labels" . | nindent 4 }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ default (include "dummy-service.istioGatewayName" .) .Values.istio_vs.gateway }}
  http:
  {{- range .Values.istio_vs.http }}
  - {{ if not .route -}}
    route:
    - destination:
        host: {{ $fullName }}
        port:
          number: {{ $.Values.port }}
    {{- end }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}