{{- if and .Values.istio_ingress.enabled (or .Values.istio_ingress.selector .Values.istio_ingress.gateway)  (.Values.istio_ingress.virtual_service).http }}
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ include "dummy-service.fullname" . }}
  labels:
      {{- include "dummy-service.labels" . | nindent 4 }}
spec:
  hosts:
  - "*"
  gateways:
  - {{ if .Values.istio_ingress.gateway }}
      {{- .Values.istio_ingress.gateway }}
    {{- else }}
      {{- include "dummy-service.fullname" . }}-gateway
    {{- end }}
  http:
  {{- range .Values.istio_ingress.virtual_service.http }}
  - {{ if not .route -}}
    route:
    - destination:
        host: {{ include "dummy-service.fullname" $ }}
        port:
          number: {{ $.Values.port }}
    {{- end }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}